// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: CoffeMachine

#ifndef _COFFEMACHINE_UI_H
#define _COFFEMACHINE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * scroll_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * scrollleft_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_latte_with_ice_cream_png);    // assets/Latte With Ice Cream.png
LV_IMG_DECLARE(ui_img_americano_png);    // assets/Americano.png
LV_IMG_DECLARE(ui_img_latte_png);    // assets/Latte.png
LV_IMG_DECLARE(ui_img_macchiato_png);    // assets/Macchiato.png
LV_IMG_DECLARE(ui_img_cappucino_png);    // assets/Cappucino.png
LV_IMG_DECLARE(ui_img_espresso_png);    // assets/Espresso.png
LV_IMG_DECLARE(ui_img_266850372);    // assets/chevron-1.png
LV_IMG_DECLARE(ui_img_chevron_png);    // assets/chevron.png
LV_IMG_DECLARE(ui_img_corner_png);    // assets/corner.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_ble_png);    // assets/ble.png
LV_IMG_DECLARE(ui_img_profile_png);    // assets/profile.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_clean_png);    // assets/clean.png
LV_IMG_DECLARE(ui_img_taste1_png);    // assets/taste1.png
LV_IMG_DECLARE(ui_img_temperature_png);    // assets/temperature.png
LV_IMG_DECLARE(ui_img_water_png);    // assets/water.png

// FONTS
LV_FONT_DECLARE(ui_font_butterchicken28);
LV_FONT_DECLARE(ui_font_butterchicken32);
LV_FONT_DECLARE(ui_font_butterchicken38);
LV_FONT_DECLARE(ui_font_butterchicken20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
