// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: CoffeMachine

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_CoffeListImg = NULL;
lv_obj_t * ui_Panel12 = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_coffe1 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_coffe2 = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_coffe3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_coffe4 = NULL;
lv_obj_t * ui_Panel5 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_coffe5 = NULL;
lv_obj_t * ui_Panel6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_coffe6 = NULL;
lv_obj_t * ui_Panel14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_coffe7 = NULL;
lv_obj_t * ui_Bingkai = NULL;
lv_obj_t * ui_Bingkai1 = NULL;
lv_obj_t * ui_Bingkai2 = NULL;
lv_obj_t * ui_Bingkai3 = NULL;
lv_obj_t * ui_Panel8 = NULL;
lv_obj_t * ui_ImgButton1 = NULL;
lv_obj_t * ui_Panel9 = NULL;
lv_obj_t * ui_ImgButton2 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Image9 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Image11 = NULL;
lv_obj_t * ui_Image12 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Image14 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Panel7 = NULL;
lv_obj_t * ui_Panel10 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_Image15 = NULL;
lv_obj_t * ui_Image16 = NULL;
lv_obj_t * ui_Panel13 = NULL;
lv_obj_t * ui_Panel11 = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Image17 = NULL;
lv_obj_t * ui_Image18 = NULL;
lv_obj_t * ui_Image19 = NULL;
lv_obj_t * ui_Image20 = NULL;
lv_obj_t * ui_Image21 = NULL;
// event funtions
void ui_event_ImgButton1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_CoffeListImg, _UI_BASIC_PROPERTY_POSITION_X,  -180);
        scroll_Animation(ui_coffe4, 0);
        scroll_Animation(ui_coffe1, 0);
        scroll_Animation(ui_coffe2, 0);
        scroll_Animation(ui_coffe3, 0);
        scroll_Animation(ui_coffe5, 0);
        scroll_Animation(ui_coffe6, 0);
        scroll_Animation(ui_coffe7, 0);
    }
}

void ui_event_ImgButton2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_basic_set_property(ui_CoffeListImg, _UI_BASIC_PROPERTY_POSITION_X,  180);
        scrollleft_Animation(ui_coffe1, 0);
        scrollleft_Animation(ui_coffe2, 0);
        scrollleft_Animation(ui_coffe3, 0);
        scrollleft_Animation(ui_coffe3, 0);
        scrollleft_Animation(ui_coffe4, 0);
        scrollleft_Animation(ui_coffe5, 0);
        scrollleft_Animation(ui_coffe6, 0);
        scrollleft_Animation(ui_coffe7, 0);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CoffeListImg = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_CoffeListImg, 1260);
    lv_obj_set_height(ui_CoffeListImg, 720);
    lv_obj_set_align(ui_CoffeListImg, LV_ALIGN_CENTER);
    lv_obj_set_scrollbar_mode(ui_CoffeListImg, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_CoffeListImg, LV_DIR_HOR);
    lv_obj_set_style_radius(ui_CoffeListImg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CoffeListImg, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CoffeListImg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CoffeListImg, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CoffeListImg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel12 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel12, 180);
    lv_obj_set_height(ui_Panel12, 720);
    lv_obj_set_x(ui_Panel12, -540);
    lv_obj_set_y(ui_Panel12, 0);
    lv_obj_set_align(ui_Panel12, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel12, lv_color_hex(0xAF9D6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel12, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 0);
    lv_obj_set_y(ui_Label13, -200);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "180 ml");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_Panel12);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 0);
    lv_obj_set_y(ui_Label14, -130);
    lv_obj_set_align(ui_Label14, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label14, "Ice Cream");
    lv_obj_set_style_text_decor(ui_Label14, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label14, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe1 = lv_image_create(ui_Panel12);
    lv_image_set_src(ui_coffe1, &ui_img_latte_with_ice_cream_png);
    lv_obj_set_x(ui_coffe1, 0);
    lv_obj_set_y(ui_coffe1, 100);
    lv_obj_set_align(ui_coffe1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel2, 180);
    lv_obj_set_height(ui_Panel2, 720);
    lv_obj_set_x(ui_Panel2, -360);
    lv_obj_set_y(ui_Panel2, 0);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x3D3B40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, 0);
    lv_obj_set_y(ui_Label3, -200);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "80 ml");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, -130);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Americano");
    lv_obj_set_style_text_decor(ui_Label4, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe2 = lv_image_create(ui_Panel2);
    lv_image_set_src(ui_coffe2, &ui_img_americano_png);
    lv_obj_set_x(ui_coffe2, 0);
    lv_obj_set_y(ui_coffe2, 100);
    lv_obj_set_align(ui_coffe2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel3 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel3, 180);
    lv_obj_set_height(ui_Panel3, 720);
    lv_obj_set_x(ui_Panel3, -180);
    lv_obj_set_y(ui_Panel3, 0);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0xAF9D6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, -200);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "140 ml");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Panel3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -130);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Cafe Latte");
    lv_obj_set_style_text_decor(ui_Label1, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe3 = lv_image_create(ui_Panel3);
    lv_image_set_src(ui_coffe3, &ui_img_latte_png);
    lv_obj_set_x(ui_coffe3, 0);
    lv_obj_set_y(ui_coffe3, 100);
    lv_obj_set_align(ui_coffe3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel4, 180);
    lv_obj_set_height(ui_Panel4, 720);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x7F6653), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 0);
    lv_obj_set_y(ui_Label5, -200);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "160 ml");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, 0);
    lv_obj_set_y(ui_Label6, -130);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Macchiato");
    lv_obj_set_style_text_decor(ui_Label6, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe4 = lv_image_create(ui_Panel4);
    lv_image_set_src(ui_coffe4, &ui_img_macchiato_png);
    lv_obj_set_x(ui_coffe4, 0);
    lv_obj_set_y(ui_coffe4, 100);
    lv_obj_set_align(ui_coffe4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel5 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel5, 180);
    lv_obj_set_height(ui_Panel5, 720);
    lv_obj_set_x(ui_Panel5, 180);
    lv_obj_set_y(ui_Panel5, 0);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x4D4144), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -200);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "140 ml");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Panel5);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 0);
    lv_obj_set_y(ui_Label8, -130);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "Cappucino");
    lv_obj_set_style_text_decor(ui_Label8, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label8, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe5 = lv_image_create(ui_Panel5);
    lv_image_set_src(ui_coffe5, &ui_img_cappucino_png);
    lv_obj_set_x(ui_coffe5, 0);
    lv_obj_set_y(ui_coffe5, 100);
    lv_obj_set_align(ui_coffe5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe5, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel6 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel6, 180);
    lv_obj_set_height(ui_Panel6, 720);
    lv_obj_set_x(ui_Panel6, 360);
    lv_obj_set_y(ui_Panel6, 0);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x6092A9), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -200);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "50 ml");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Panel6);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 0);
    lv_obj_set_y(ui_Label10, -130);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Espresso");
    lv_obj_set_style_text_decor(ui_Label10, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe6 = lv_image_create(ui_Panel6);
    lv_image_set_src(ui_coffe6, &ui_img_espresso_png);
    lv_obj_set_x(ui_coffe6, 0);
    lv_obj_set_y(ui_coffe6, 100);
    lv_obj_set_align(ui_coffe6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe6, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel14 = lv_obj_create(ui_CoffeListImg);
    lv_obj_set_width(ui_Panel14, 180);
    lv_obj_set_height(ui_Panel14, 720);
    lv_obj_set_x(ui_Panel14, 540);
    lv_obj_set_y(ui_Panel14, 0);
    lv_obj_set_align(ui_Panel14, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel14, lv_color_hex(0x3D3B40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel14, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel14, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label15 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 0);
    lv_obj_set_y(ui_Label15, -200);
    lv_obj_set_align(ui_Label15, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label15, "120 ml");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_butterchicken28, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_Panel14);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 0);
    lv_obj_set_y(ui_Label16, -130);
    lv_obj_set_align(ui_Label16, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label16, "Irish Coffe");
    lv_obj_set_style_text_decor(ui_Label16, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label16, &ui_font_butterchicken38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_coffe7 = lv_image_create(ui_Panel14);
    lv_image_set_src(ui_coffe7, &ui_img_latte_with_ice_cream_png);
    lv_obj_set_x(ui_coffe7, 0);
    lv_obj_set_y(ui_coffe7, 100);
    lv_obj_set_align(ui_coffe7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_coffe7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_coffe7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Bingkai = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Bingkai, 720);
    lv_obj_set_height(ui_Bingkai, 7);
    lv_obj_set_x(ui_Bingkai, 0);
    lv_obj_set_y(ui_Bingkai, -357);
    lv_obj_set_align(ui_Bingkai, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Bingkai, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Bingkai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bingkai, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bingkai, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bingkai, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bingkai, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bingkai, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bingkai1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Bingkai1, 720);
    lv_obj_set_height(ui_Bingkai1, 7);
    lv_obj_set_x(ui_Bingkai1, 0);
    lv_obj_set_y(ui_Bingkai1, 356);
    lv_obj_set_align(ui_Bingkai1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Bingkai1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Bingkai1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bingkai1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bingkai1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bingkai1, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bingkai1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bingkai1, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bingkai2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Bingkai2, 7);
    lv_obj_set_height(ui_Bingkai2, 720);
    lv_obj_set_x(ui_Bingkai2, -357);
    lv_obj_set_y(ui_Bingkai2, 0);
    lv_obj_set_align(ui_Bingkai2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Bingkai2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Bingkai2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bingkai2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bingkai2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bingkai2, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bingkai2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bingkai2, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bingkai3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Bingkai3, 7);
    lv_obj_set_height(ui_Bingkai3, 720);
    lv_obj_set_x(ui_Bingkai3, 356);
    lv_obj_set_y(ui_Bingkai3, 0);
    lv_obj_set_align(ui_Bingkai3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Bingkai3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Bingkai3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Bingkai3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bingkai3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Bingkai3, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Bingkai3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Bingkai3, 7, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel8, 120);
    lv_obj_set_height(ui_Panel8, 70);
    lv_obj_set_x(ui_Panel8, 324);
    lv_obj_set_y(ui_Panel8, -200);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton1 = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_ImgButton1, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_266850372, NULL);
    lv_obj_set_width(ui_ImgButton1, 48);
    lv_obj_set_height(ui_ImgButton1, 50);
    lv_obj_set_x(ui_ImgButton1, 294);
    lv_obj_set_y(ui_ImgButton1, -200);
    lv_obj_set_align(ui_ImgButton1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton1, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ImgButton1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImgButton1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel9, 120);
    lv_obj_set_height(ui_Panel9, 70);
    lv_obj_set_x(ui_Panel9, -324);
    lv_obj_set_y(ui_Panel9, -200);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel9, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton2 = lv_imagebutton_create(ui_Screen1);
    lv_imagebutton_set_src(ui_ImgButton2, LV_IMAGEBUTTON_STATE_RELEASED, NULL, &ui_img_chevron_png, NULL);
    lv_obj_set_width(ui_ImgButton2, 48);
    lv_obj_set_height(ui_ImgButton2, 50);
    lv_obj_set_x(ui_ImgButton2, -294);
    lv_obj_set_y(ui_ImgButton2, -200);
    lv_obj_set_align(ui_ImgButton2, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_ImgButton2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_ImgButton2, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ImgButton2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ImgButton2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ImgButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ImgButton2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image8, &ui_img_corner_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image8, -317);
    lv_obj_set_y(ui_Image8, -317);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image7 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image7, &ui_img_corner_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image7, 316);
    lv_obj_set_y(ui_Image7, -316);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image7, 900);

    ui_Image9 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image9, &ui_img_corner_png);
    lv_obj_set_width(ui_Image9, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image9, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image9, -316);
    lv_obj_set_y(ui_Image9, 316);
    lv_obj_set_align(ui_Image9, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image9, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image9, -900);

    ui_Image10 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image10, &ui_img_corner_png);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image10, 316);
    lv_obj_set_y(ui_Image10, 315);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image10, -1800);

    ui_Image11 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image11, &ui_img_corner_png);
    lv_obj_set_width(ui_Image11, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image11, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image11, -334);
    lv_obj_set_y(ui_Image11, -251);
    lv_obj_set_align(ui_Image11, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image11, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image11, -900);
    lv_image_set_scale(ui_Image11, 128);

    ui_Image12 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image12, &ui_img_corner_png);
    lv_obj_set_width(ui_Image12, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image12, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image12, -336);
    lv_obj_set_y(ui_Image12, -149);
    lv_obj_set_align(ui_Image12, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image12, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image12, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_Image12, 128);

    ui_Image13 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image13, &ui_img_corner_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image13, 335);
    lv_obj_set_y(ui_Image13, -254);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image13, -1800);
    lv_image_set_scale(ui_Image13, 128);

    ui_Image14 = lv_image_create(ui_Screen1);
    lv_image_set_src(ui_Image14, &ui_img_corner_png);
    lv_obj_set_width(ui_Image14, LV_SIZE_CONTENT);   /// 76
    lv_obj_set_height(ui_Image14, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_Image14, 334);
    lv_obj_set_y(ui_Image14, -147);
    lv_obj_set_align(ui_Image14, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image14, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image14, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_Image14, 900);
    lv_image_set_scale(ui_Image14, 128);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 360);
    lv_obj_set_height(ui_Panel1, 15);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -347);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel7, 360);
    lv_obj_set_height(ui_Panel7, 40);
    lv_obj_set_x(ui_Panel7, 0);
    lv_obj_set_y(ui_Panel7, -340);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_Panel7);
    lv_obj_set_width(ui_Panel10, 180);
    lv_obj_set_height(ui_Panel10, 26);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0xAF9D6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label11, -20);
    lv_obj_set_y(ui_Label11, 0);
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "PPA & DMA :");
    lv_obj_set_style_text_color(ui_Label11, lv_color_hex(0xAF9D6F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label11, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 61);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "ON");
    lv_obj_set_style_text_font(ui_Label12, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image15 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image15, &ui_img_wifi_png);
    lv_obj_set_width(ui_Image15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image15, 138);
    lv_obj_set_y(ui_Image15, -1);
    lv_obj_set_align(ui_Image15, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image15, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image15, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image16 = lv_image_create(ui_Panel7);
    lv_image_set_src(ui_Image16, &ui_img_ble_png);
    lv_obj_set_width(ui_Image16, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image16, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image16, -139);
    lv_obj_set_y(ui_Image16, 0);
    lv_obj_set_align(ui_Image16, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image16, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image16, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel13 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel13, 360);
    lv_obj_set_height(ui_Panel13, 18);
    lv_obj_set_x(ui_Panel13, 0);
    lv_obj_set_y(ui_Panel13, 344);
    lv_obj_set_align(ui_Panel13, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel13, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel13, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel11 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel11, 360);
    lv_obj_set_height(ui_Panel11, 40);
    lv_obj_set_x(ui_Panel11, 0);
    lv_obj_set_y(ui_Panel11, 332);
    lv_obj_set_align(ui_Panel11, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel11, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel11, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel11, lv_color_hex(0x282730), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel11, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image1, &ui_img_profile_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 138);
    lv_obj_set_y(ui_Image1, -1);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image17, &ui_img_settings_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_Image17, -139);
    lv_obj_set_y(ui_Image17, 0);
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image18 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image18, &ui_img_clean_png);
    lv_obj_set_width(ui_Image18, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image18, -23);
    lv_obj_set_y(ui_Image18, 0);
    lv_obj_set_align(ui_Image18, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image18, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image19, &ui_img_taste1_png);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image19, -87);
    lv_obj_set_y(ui_Image19, 0);
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image20, &ui_img_temperature_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image20, 39);
    lv_obj_set_y(ui_Image20, 0);
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image21 = lv_image_create(ui_Panel11);
    lv_image_set_src(ui_Image21, &ui_img_water_png);
    lv_obj_set_width(ui_Image21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image21, 88);
    lv_obj_set_y(ui_Image21, 3);
    lv_obj_set_align(ui_Image21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image21, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Image21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_ImgButton1, ui_event_ImgButton1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton2, ui_event_ImgButton2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_CoffeListImg = NULL;
    ui_Panel12 = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_coffe1 = NULL;
    ui_Panel2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_coffe2 = NULL;
    ui_Panel3 = NULL;
    ui_Label2 = NULL;
    ui_Label1 = NULL;
    ui_coffe3 = NULL;
    ui_Panel4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_coffe4 = NULL;
    ui_Panel5 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_coffe5 = NULL;
    ui_Panel6 = NULL;
    ui_Label9 = NULL;
    ui_Label10 = NULL;
    ui_coffe6 = NULL;
    ui_Panel14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_coffe7 = NULL;
    ui_Bingkai = NULL;
    ui_Bingkai1 = NULL;
    ui_Bingkai2 = NULL;
    ui_Bingkai3 = NULL;
    ui_Panel8 = NULL;
    ui_ImgButton1 = NULL;
    ui_Panel9 = NULL;
    ui_ImgButton2 = NULL;
    ui_Image8 = NULL;
    ui_Image7 = NULL;
    ui_Image9 = NULL;
    ui_Image10 = NULL;
    ui_Image11 = NULL;
    ui_Image12 = NULL;
    ui_Image13 = NULL;
    ui_Image14 = NULL;
    ui_Panel1 = NULL;
    ui_Panel7 = NULL;
    ui_Panel10 = NULL;
    ui_Label11 = NULL;
    ui_Label12 = NULL;
    ui_Image15 = NULL;
    ui_Image16 = NULL;
    ui_Panel13 = NULL;
    ui_Panel11 = NULL;
    ui_Image1 = NULL;
    ui_Image17 = NULL;
    ui_Image18 = NULL;
    ui_Image19 = NULL;
    ui_Image20 = NULL;
    ui_Image21 = NULL;

}
