// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: CoffeMachine

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_CoffeListImg;
extern lv_obj_t * ui_Panel12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_coffe1;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_coffe2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_coffe3;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_coffe4;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_coffe5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_coffe6;
extern lv_obj_t * ui_Panel14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_coffe7;
extern lv_obj_t * ui_Bingkai;
extern lv_obj_t * ui_Bingkai1;
extern lv_obj_t * ui_Bingkai2;
extern lv_obj_t * ui_Bingkai3;
extern lv_obj_t * ui_Panel8;
extern void ui_event_ImgButton1(lv_event_t * e);
extern lv_obj_t * ui_ImgButton1;
extern lv_obj_t * ui_Panel9;
extern void ui_event_ImgButton2(lv_event_t * e);
extern lv_obj_t * ui_ImgButton2;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_Image12;
extern lv_obj_t * ui_Image13;
extern lv_obj_t * ui_Image14;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_Image16;
extern lv_obj_t * ui_Panel13;
extern lv_obj_t * ui_Panel11;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Image17;
extern lv_obj_t * ui_Image18;
extern lv_obj_t * ui_Image19;
extern lv_obj_t * ui_Image20;
extern lv_obj_t * ui_Image21;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

